server:
  port: 8001
spring:
  application:
    name:  dubbo-springboot-demo-provider
  profiles:
    active: dev
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: N/A
  scan:
    base-packages: org.apache.dubbo.springboot.demo.provider
